name: Workflow to run unit tests on push
on: push
jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test
      DB_TEST_URL: jdbc:mysql://127.0.0.1:3306/rewards_app_test
      DB_USER: test_user
      DB_PASSWORD: test_password
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      JWT_EXPIRES_IN: "3600000"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Maven clean and test
        run: mvn clean test